"""removed comment section for task

Revision ID: 0d409cd4f893
Revises: 5a890d973552
Create Date: 2026-04-03 16:52:37.565282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d409cd4f893'
down_revision: Union[str, Sequence[str], None] = '5a890d973552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
