services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  parser:
    build:
      context: ./parser
    env_file: .env
    ports:
      - "8001:8001"
    restart: unless-stopped

  api:
    build:
      context: ./fastapi
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      parser:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery:
    build:
      context: ./fastapi
    command: celery -A celery_app.celery worker --loglevel=info
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
